{
 "title": "Sonar Results",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "Application",
    "query": "SHOW TAG VALUES WITH KEY = \"key\" where \"key\" =~ /[a-z]*.develop/ or \"key\" =~ /mmm.*/"
   }
  ]
 },
 "panels": [
  {
   "title": "Open Issues",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "alias": "$tag_key",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(value) FROM \"open_issues\" WHERE (\"key\" =~ /^$Application$/) and $timeFilter GROUP BY time(15m) order by time desc limit 1",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Complexity",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "alias": "$tag_key",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(value) FROM \"complexity\" WHERE (\"key\" =~ /^$Application$/) and $timeFilter GROUP BY time(15m) order by time desc limit 1",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Coverage",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 5, "x": 10, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "alias": "$tag_key",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(value) FROM \"coverage\" WHERE (\"key\" =~ /^$Application$/) and $timeFilter GROUP BY time(15m) order by time desc limit 1",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Coverage on New Code",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 5, "x": 15, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "alias": "$tag_key",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(value) FROM \"new_coverage\" WHERE (\"key\" =~ /^$Application$/) and $timeFilter GROUP BY time(15m) order by time desc limit 1",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Duplicated Lines Density",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "alias": "$tag_key",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(value) FROM \"duplicated_lines_density\" WHERE (\"key\" =~ /^$Application$/) and $timeFilter GROUP BY time(15m) order by time desc limit 1",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Blocker",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 6 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "alias": "$tag_key",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(value) FROM \"blocker_violations\" WHERE (\"key\" =~ /^$Application$/) and $timeFilter GROUP BY time(15m) ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Critical",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 6 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "alias": "$tag_key",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(value) FROM \"critical_violations\" WHERE (\"key\" =~ /^$Application$/) and $timeFilter GROUP BY time(15m) ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Major",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 5, "x": 10, "y": 6 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "alias": "$tag_key",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(value) FROM \"major_violations\" WHERE (\"key\" =~ /^$Application$/) and $timeFilter GROUP BY time(15m) ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Minor",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 5, "x": 15, "y": 6 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "alias": "$tag_key",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(value) FROM \"minor_violations\" WHERE (\"key\" =~ /^$Application$/) and $timeFilter GROUP BY time(15m) ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Info",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 6 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "alias": "$tag_key",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(value) FROM \"info_violations\" WHERE (\"key\" =~ /^$Application$/) and $timeFilter GROUP BY time(15m) ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Bugs",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 11 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "alias": "$tag_key",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(value) FROM \"bugs\" WHERE (\"key\" =~ /^$Application$/) and $timeFilter GROUP BY time(15m) order by time desc limit 1",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Code Smells",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 11 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "alias": "$tag_key",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(value) FROM \"code_smells\" WHERE (\"key\" =~ /^$Application$/) and $timeFilter GROUP BY time(15m) order by time desc limit 1",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Duplicated Lines",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 5, "x": 10, "y": 11 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "alias": "$tag_key",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(value) FROM \"duplicated_lines\" WHERE (\"key\" =~ /^$Application$/) and $timeFilter GROUP BY time(15m) order by time desc limit 1",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Lines to Cover",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 5, "x": 15, "y": 11 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "alias": "$tag_key",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(value) FROM \"lines_to_cover\" WHERE (\"key\" =~ /^$Application$/) and $timeFilter GROUP BY time(15m) order by time desc limit 1",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Lines of Code",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 11 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "alias": "$tag_key",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(value) FROM \"ncloc\" WHERE (\"key\" =~ /^$Application$/) and $timeFilter GROUP BY time(15m) order by time desc limit 1",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Open Issues (Evaluation)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"value\") FROM open_issues WHERE (\"key\" =~ /^$Application$/) and $timeFilter GROUP BY time(15m)  ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Complexity  (Evaluation)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 7, "y": 16 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"value\") FROM complexity WHERE (\"key\" =~ /^$Application$/) and $timeFilter GROUP BY time(15m)  ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Test Coverage  (Evaluation)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 16 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"value\") FROM coverage WHERE (\"key\" =~ /^$Application$/) and $timeFilter GROUP BY time(15m)  ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}